# Numpy - Intro - Practicals

In [7]:
# Create a NumPy array with 5 elements of your choice.

import numpy as np

arr = np.array([1,2,3,3,5])
arr

arr[4]

5

In [12]:
# Use the np.random.randint function to create a 2D array of size (3,4) with random integers between 0 and 10.

arr_1 = np.random.randint(11, size=(3,4), dtype=int)
arr_1


array([[ 8,  1,  0,  0],
       [ 0,  8,  6,  2],
       [10,  2,  9,  1]])

## Numpy - Array Operations - Practicals

In [21]:
# Create a NumPy array of random numbers with dimensions 6 x 10. Call it my_array
my_array = np.random.randint(101, size=(6,10), dtype=int)
my_array

array([[18, 99, 99, 30, 63, 10, 75, 88, 13, 73],
       [14,  1, 63, 88, 54, 47,  3, 20, 80, 54],
       [59,  6, 54, 80, 90, 24, 73, 95, 55, 55],
       [48,  9, 87, 70, 79, 89, 83, 82,  2, 29],
       [12, 27,  1, 20, 69, 50,  8, 13, 97, 86],
       [ 9, 22, 79, 47, 68, 37, 94, 10, 45, 48]])

In [24]:
# Slice out the 1st, 3rd and 5th column of the array into as new array. Call it new_array

new_array = my_array[:, [1, 3, 5]]

new_array

print(new_array.shape)

(6, 3)


In [25]:
# Try to multiply my_array x new_array. Does it work? If not, do you know why?

np.multiply(my_array, new_array)



ValueError: operands could not be broadcast together with shapes (6,10) (6,3) 

In [26]:
# Transpose new_array and try again. Does it work now?

np.transpose(new_array)



array([[99,  1,  6,  9, 27, 22],
       [30, 88, 80, 70, 20, 47],
       [10, 47, 24, 89, 50, 37]])

In [28]:
my_array*new_array

ValueError: operands could not be broadcast together with shapes (6,10) (6,3) 

In [30]:
# Create a NumPy array of dimensions 5 x 5 where each element is a zero.
arr1 = np.full((5, 5), fill_value = 0)

arr1


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
# Replace the left diagonal of the array with 1s.

arr1 = np.eye(arr1.shape[1], dtype='int64') 
arr1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [35]:
# Create a 3D array of size (3,4,5) and use slicing to select the first two elements of the last dimension.

three_d_array = np.random.randint(101, size=(3,4,5), dtype=int)

three_d_array

array([[[13, 10, 68, 84, 75],
        [61, 76, 77, 37, 58],
        [54, 77, 53, 58, 98],
        [ 5, 20, 56, 56, 33]],

       [[57, 55, 62, 98, 25],
        [90, 61, 86, 15,  8],
        [89, 49, 29,  8, 89],
        [49, 79, 89, 25, 15]],

       [[84, 16, 31, 86, 46],
        [55, 18, 72, 95, 36],
        [95, 21, 54, 39, 76],
        [ 8, 61, 19, 29, 27]]])

In [44]:
three_d_array[2]

array([[84, 16, 31, 86, 46],
       [55, 18, 72, 95, 36],
       [95, 21, 54, 39, 76],
       [ 8, 61, 19, 29, 27]])

In [56]:
three_d_array[2][0, 0:2]

array([84, 16])

## Numpy - Reshape and Broadcasting - Practicals

In [61]:
arr_2 = np.random.randint(20, size=(1,10), dtype=int)
arr_2

array([[19, 15,  4,  0, 10,  4,  0,  7,  7,  3]])

In [62]:
arr_2.reshape(2,5)

array([[19, 15,  4,  0, 10],
       [ 4,  0,  7,  7,  3]])

In [64]:
# Create a second NumPy array with 5 elements, and join it to the first array using the concatenate function.

arr_3 = np.random.randint(20, size=(1,5), dtype=int)
arr_3

array([[17, 11,  0, 16,  8]])

In [68]:
np.concatenate((arr_2, arr_3), axis=1)

array([[19, 15,  4,  0, 10,  4,  0,  7,  7,  3, 17, 11,  0, 16,  8]])

In [70]:
# Create two arrays of size (2,3) and broadcast them together to create an array of size (2,3,3).

arr_3 = np.random.randint(40, size=(2,3), dtype=int)
arr_3

array([[35, 34,  2],
       [35, 33, 33]])

In [71]:
arr_4 = np.random.randint(60, size=(2,3), dtype=int)
arr_4

array([[51,  4, 20],
       [44, 29, 41]])

In [73]:
result = arr_3 * arr_4
result

array([[1785,  136,   40],
       [1540,  957, 1353]])