## PyTorch Tensors

In [1]:
import torch

In [21]:
# Create a Random Torch Tensor of Size 4x2x3. Define a variable called my_tensor with this size. Print its shape.

my_tensor = torch.randn(4,2,3)
my_tensor
# my_tensor.shape

tensor([[[ 0.8472, -0.8570,  1.1241],
         [ 0.8102, -0.6924,  0.4297]],

        [[-1.2875, -0.2553, -1.9132],
         [ 0.5703,  0.4412, -1.1951]],

        [[ 0.6580,  2.0512,  0.2503],
         [-0.2114, -2.1752, -0.7314]],

        [[-0.3528, -0.9771, -0.1244],
         [ 0.9970,  1.8457,  1.8206]]])

In [22]:
# Float Tensor to Double Tensor. Define a tensor called my_tensor from one that contains floating point numbers to one that contains double precision floating point numbers.
my_tensor.float()
# my_tensor = my_tensor.double()
# my_tensor

tensor([[[ 0.8472, -0.8570,  1.1241],
         [ 0.8102, -0.6924,  0.4297]],

        [[-1.2875, -0.2553, -1.9132],
         [ 0.5703,  0.4412, -1.1951]],

        [[ 0.6580,  2.0512,  0.2503],
         [-0.2114, -2.1752, -0.7314]],

        [[-0.3528, -0.9771, -0.1244],
         [ 0.9970,  1.8457,  1.8206]]])

In [23]:
my_tensor = my_tensor.double()
my_tensor

tensor([[[ 0.8472, -0.8570,  1.1241],
         [ 0.8102, -0.6924,  0.4297]],

        [[-1.2875, -0.2553, -1.9132],
         [ 0.5703,  0.4412, -1.1951]],

        [[ 0.6580,  2.0512,  0.2503],
         [-0.2114, -2.1752, -0.7314]],

        [[-0.3528, -0.9771, -0.1244],
         [ 0.9970,  1.8457,  1.8206]]], dtype=torch.float64)